repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=88]
        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=88"]
        language_version: python3.12

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(json|yaml|yml|md|js|css|html|ts|tsx|jsx)$
default_stages: [pre-commit]

exclude: |
  (?x)^(
    plants_classification/1/.*/checkpoints/.*\.ckpt |
    plants_classification/checkpoints/.*\.ckpt |
    plants_classification/.*/checkpoints/.*\.ckpt
  )$
