infer:
  model:
    checkpoint_path: "outputs/models/flower-resnet50-epoch=01-val_loss=0.50.ckpt"
  image_path: "test_image.jpg"
  top_k: 5
  preprocess:
    resize: 256
    crop_size: 224
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
