infer:
  model:
    checkpoint_path: "checkpoints/best-epoch=1.ckpt"
  image_path: "../data/flowers-102/jpg/image_00001.jpg"
  top_k: 5
  preprocess:
    resize: 256
    crop_size: 224
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
